version: '3'
services:
  client:
    image: dylnorris19/client
    build:
      context: ./client
    ports:
      - "5173:5173"
    env_file:
      - .env
    # If you need specific environment variables for client:
    # environment:
    #   - CLIENT_ENV_VAR=value

  server:
    image: dylnorris19/server
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    # If you need specific environment variables for server:
    # environment:
    #   - SERVER_ENV_VAR=value
networks:
  default:
    attachable: true