version: '3'
services:
  client:
    image: dylnorris19/client
    build:
      context: ./client
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    image: dylnorris19/server
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
networks:
  default:
    attachable: true